services: 
  - type: web 
    name: nonchalant-hoodie 
    env: python 
    buildCommand: pip install -r requirements.txt 
    startCommand: cd Nonecom && gunicorn Nonecom.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.14
      - key: POETRY_ENABLED
        value: false
      - key: PYTHONPATH
        value: /opt/render/project/src/Nonecom
